import { deleteEmailOAuthToken, isEmailOAuthConfigured, linkEmailAccount, setRealAutoReply } from "@/services/emailOAuthService";
import type { EmailAccount, EmailProvider } from "@/types/hold";

export interface ConnectAccountResult {
  ok: boolean;
  reason?: "work-blocked" | "oauth-unavailable" | "oauth-cancelled";
  linkedAt?: number;
}

/**
 * Real OAuth when a provider is configured (see emailOAuthService.ts —
 * gated on EXPO_PUBLIC_GOOGLE_OAUTH_CLIENT_ID / EXPO_PUBLIC_MICROSOFT_OAUTH_CLIENT_ID,
 * neither set yet), honest fallback to a purely local/manual account
 * otherwise — same "nothing is sent automatically yet" framing this always
 * had (see EmailOutOfOffice.tsx's own subtext), now conditional on real
 * configuration rather than unconditional. `accountId` is generated by the
 * caller before this runs (EmailOutOfOffice.tsx), not here — the OAuth
 * token needs an id to key against from the moment the flow starts, before
 * this function has any result to hand one back.
 *
 * The "work account blocked" simulation is kept, narrowed to Gmail only —
 * there's no genuine signal available pre-consent for a Google Workspace
 * account's own access policy, so the personal/work choice in the UI still
 * stands in for that. Outlook work accounts go through the real flow
 * unmodified: an Azure AD tenant that blocks third-party app consent
 * enforces that itself, during the flow, no simulation needed. See
 * docs/09-decision-log.md, 2026-08-21.
 */
export async function connectEmailAccount(
  provider: EmailProvider,
  isWork: boolean,
  accountId: string
): Promise<ConnectAccountResult> {
  if (isWork && provider === "gmail") {
    return { ok: false, reason: "work-blocked" };
  }

  if (!isEmailOAuthConfigured(provider)) {
    return { ok: true };
  }

  const result = await linkEmailAccount(provider, accountId);
  if (!result.ok) return { ok: false, reason: "oauth-cancelled" };

  return { ok: true, linkedAt: Date.now() };
}

/** Real per-account provider API call for every enabled, linked account (EmailAccount.linkedAt set); manual-only accounts are silently skipped — there's no API to call for those, the person manages their own out-of-office by hand from the drafted text. */
export async function activateOutOfOffice(accounts: EmailAccount[]): Promise<void> {
  await Promise.all(
    accounts
      .filter((account) => account.enabled && account.linkedAt !== undefined)
      .map((account) => setRealAutoReply(account.id, account.provider, true, account.message))
  );
}

/** Symmetric to activateOutOfOffice, called from Reconnect with the minimal id+provider pairs persisted onto the period at Going Quiet's Done step (HoldPeriod.emailLinkedAccounts) — Reconnect never has the full EmailAccount records, which are Going Quiet's own local, per-session state. */
export async function deactivateOutOfOffice(accounts: { id: string; provider: EmailProvider }[]): Promise<void> {
  await Promise.all(accounts.map((account) => setRealAutoReply(account.id, account.provider, false, "")));
}

export async function deleteLinkedAccountToken(accountId: string): Promise<void> {
  await deleteEmailOAuthToken(accountId);
}

export function createEmailAccountId(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
