import * as SecureStore from "expo-secure-store";
import {
  fetchLinkedEmailAddress,
  getLinkedEmailAccountIds,
  isEmailOAuthConfigured,
  linkEmailAccount,
  setRealAutoReply
} from "@/services/emailOAuthService";
import type { EmailAccount, EmailProvider } from "@/types/hold";

const ACCOUNTS_KEY = "hold.widerWorld.emailAccounts";
const MIGRATION_DONE_KEY = "hold.widerWorld.emailAccounts.migrated";

async function writeAccounts(accounts: EmailAccount[]): Promise<void> {
  await SecureStore.setItemAsync(ACCOUNTS_KEY, JSON.stringify(accounts));
}

/** Durable as of 2026-08-30 — configured once in Settings, not re-entered every Going Quiet session. Runs migrateLinkedEmailAccounts on first call in a given app lifetime isn't guaranteed here; call that explicitly at a stable point (Settings screen mount) instead, so its own report is visible rather than silent. */
export async function getEmailAccounts(): Promise<EmailAccount[]> {
  const raw = await SecureStore.getItemAsync(ACCOUNTS_KEY);
  return raw ? (JSON.parse(raw) as EmailAccount[]) : [];
}

export async function addEmailAccount(account: EmailAccount): Promise<EmailAccount[]> {
  const current = await getEmailAccounts();
  const next = [...current, account];
  await writeAccounts(next);
  return next;
}

export async function updateEmailAccount(id: string, patch: Partial<EmailAccount>): Promise<EmailAccount[]> {
  const current = await getEmailAccounts();
  const next = current.map((account) => (account.id === id ? { ...account, ...patch } : account));
  await writeAccounts(next);
  return next;
}

export async function removeEmailAccount(id: string): Promise<EmailAccount[]> {
  const current = await getEmailAccounts();
  const next = current.filter((account) => account.id !== id);
  await writeAccounts(next);
  return next;
}

export interface EmailAccountMigrationResult {
  /** Accounts found linked via a real OAuth token that had no durable record yet, now created. Empty whenever this has already run once, or nothing was ever really linked (the common case today — OAuth isn't configured, see emailOAuthService.ts). */
  migratedAccounts: EmailAccount[];
}

/**
 * One-time migration (2026-08-30): EmailAccount records used to be fully
 * ephemeral, per-Going-Quiet-session local state — only the real OAuth
 * token itself (emailOAuthService.ts's own token index) ever survived
 * between sessions. This finds every account id that index knows about but
 * this durable store doesn't, and creates a real record for each rather
 * than treating a genuine, working connection as absent just because its
 * old label/enabled state was never saved anywhere. Label defaults to the
 * account's real email address (fetched live via the provider's own
 * profile API) when that succeeds, or a generic "Gmail account"/"Outlook
 * account" when it doesn't — never a reason to drop the connection itself.
 * Idempotent and safe to call every time the Settings screen mounts: a
 * MIGRATION_DONE flag means every subsequent call is a fast, empty no-op,
 * not a repeated scan. See docs/09-decision-log.md.
 */
export async function migrateLinkedEmailAccounts(): Promise<EmailAccountMigrationResult> {
  const alreadyMigrated = await SecureStore.getItemAsync(MIGRATION_DONE_KEY);
  if (alreadyMigrated) return { migratedAccounts: [] };

  const [linkedIds, existing] = await Promise.all([getLinkedEmailAccountIds(), getEmailAccounts()]);
  const existingIds = new Set(existing.map((account) => account.id));
  const missing = linkedIds.filter((entry) => !existingIds.has(entry.accountId));

  const migratedAccounts: EmailAccount[] = await Promise.all(
    missing.map(async ({ accountId, provider }) => {
      const address = await fetchLinkedEmailAddress(accountId, provider);
      return {
        id: accountId,
        label: address ?? (provider === "gmail" ? "Gmail account" : "Outlook account"),
        provider,
        enabled: true,
        linkedAt: Date.now()
      };
    })
  );

  if (migratedAccounts.length > 0) {
    await writeAccounts([...existing, ...migratedAccounts]);
  }
  await SecureStore.setItemAsync(MIGRATION_DONE_KEY, "true");

  return { migratedAccounts };
}

export interface ConnectAccountResult {
  ok: boolean;
  reason?: "work-blocked" | "oauth-unavailable" | "oauth-cancelled";
  linkedAt?: number;
}

/**
 * Real OAuth when a provider is configured (see emailOAuthService.ts —
 * gated on EXPO_PUBLIC_GOOGLE_OAUTH_CLIENT_ID / EXPO_PUBLIC_MICROSOFT_OAUTH_CLIENT_ID,
 * neither set yet), honest fallback to a purely local/manual account
 * otherwise — same "nothing is sent automatically yet" framing this always
 * had (see EmailOutOfOffice.tsx's own subtext), now conditional on real
 * configuration rather than unconditional. `accountId` is generated by the
 * caller before this runs (EmailOutOfOffice.tsx), not here — the OAuth
 * token needs an id to key against from the moment the flow starts, before
 * this function has any result to hand one back.
 *
 * The "work account blocked" simulation is kept, narrowed to Gmail only —
 * there's no genuine signal available pre-consent for a Google Workspace
 * account's own access policy, so the personal/work choice in the UI still
 * stands in for that. Outlook work accounts go through the real flow
 * unmodified: an Azure AD tenant that blocks third-party app consent
 * enforces that itself, during the flow, no simulation needed. See
 * docs/09-decision-log.md, 2026-08-21.
 */
export async function connectEmailAccount(
  provider: EmailProvider,
  isWork: boolean,
  accountId: string
): Promise<ConnectAccountResult> {
  if (isWork && provider === "gmail") {
    return { ok: false, reason: "work-blocked" };
  }

  if (!isEmailOAuthConfigured(provider)) {
    return { ok: true };
  }

  const result = await linkEmailAccount(provider, accountId);
  if (!result.ok) return { ok: false, reason: "oauth-cancelled" };

  return { ok: true, linkedAt: Date.now() };
}

/**
 * Real per-account provider API call for every enabled, linked account
 * (EmailAccount.linkedAt set); manual-only accounts are silently skipped —
 * there's no API to call for those, the person manages their own
 * out-of-office by hand from the drafted text. `message` is resolved by
 * the caller, not read from the account record — as of 2026-08-30 an
 * account has no message of its own, it uses whichever Context it's
 * selected into.
 */
export async function activateOutOfOffice(accounts: (EmailAccount & { message: string })[]): Promise<void> {
  await Promise.all(
    accounts
      .filter((account) => account.enabled && account.linkedAt !== undefined)
      .map((account) => setRealAutoReply(account.id, account.provider, true, account.message))
  );
}

/** Symmetric to activateOutOfOffice, called from Reconnect with the minimal id+provider pairs persisted onto the period at Going Quiet's Done step (HoldPeriod.emailLinkedAccounts) — Reconnect never has the full EmailAccount records, which are Going Quiet's own local, per-session state. */
export async function deactivateOutOfOffice(accounts: { id: string; provider: EmailProvider }[]): Promise<void> {
  await Promise.all(accounts.map((account) => setRealAutoReply(account.id, account.provider, false, "")));
}

export function createEmailAccountId(): string {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`;
}
