import {
  createContext,
  type PropsWithChildren,
  useContext,
  useMemo,
  useState
} from "react";
import type {
  AudienceCircle,
  AudienceContact,
  CircleGroup,
  FlowMode,
  GoingQuietRecipient,
  HoldFlowState,
  ReturnStyle
} from "@/types/hold";

interface HoldFlowContextValue extends HoldFlowState {
  setRecipients: (recipients: string[]) => void;
  toggleGroup: (group: CircleGroup) => Promise<void>;
  /**
   * Replaces the whole selection in one atomic step — for bulk operations
   * ("All", restoring a prior selection) that need to land in one render,
   * not N sequential `toggleGroup` calls. A loop of individually-awaited
   * `toggleGroup` calls is genuinely unsafe for this: each one reads
   * `selectedGroups` fresh from the CALLER's own render closure, and since
   * `toggleGroup` itself no longer does any real async work, successive
   * calls can resolve faster than React re-renders the caller with the
   * previous call's result — so a rapid loop ends up non-deterministic
   * about which Circles it actually toggles (confirmed as the root cause
   * of a real "All" bug, 2026-08-11). See docs/09-decision-log.md.
   */
  setSelectedGroups: (groups: CircleGroup[]) => void;
  /**
   * Replaces one already-selected Circle's own data in place (e.g. after
   * adding a member to it mid-flow) — `toggleGroup`/`setSelectedGroups`
   * only ever use whatever CircleGroup object the caller already has, they
   * never refetch from storage themselves, so without this, a newly-added
   * member wouldn't appear in `goingQuietRecipients` until the Circle was
   * deselected and reselected. See docs/09-decision-log.md, 2026-08-11.
   */
  updateSelectedGroup: (updatedGroup: CircleGroup) => void;
  /**
   * `fallbackMessage` pre-fills the excluded recipient's own instant message
   * — the currently active shared group message, passed in by the caller
   * rather than looked up here, since the shared message is now owned by
   * the screen (one flat text per current Circle-combination selection),
   * not a per-Circle draft in this context. See docs/09-decision-log.md,
   * 2026-08-11.
   */
  toggleRecipientIncluded: (contactId: string, fallbackMessage: string) => void;
  setRecipientIndividuallyRemoved: (contactId: string, removed: boolean) => void;
  setRecipientInstantMessage: (contactId: string, message: string) => void;
  setRecipientRouteToPersonalise: (contactId: string, route: boolean) => void;
  /**
   * Bundles one or more already-removed recipients into a new provisional
   * Circle mid-flow — the "+ New circle from selected" action. Synchronous:
   * the placeholder name is auto-generated by the caller, no contact picker
   * or template lookup involved. See docs/09-decision-log.md, 2026-08-11.
   */
  splitRecipientsIntoNewCircle: (contactIds: string[], group: CircleGroup) => void;
  setReturnStyle: (style: ReturnStyle) => void;
  setAudience: (circles: AudienceCircle[], ungrouped: AudienceContact[], periodId: string | null) => void;
  resetFlow: (mode: FlowMode) => void;
}

const initialState: HoldFlowState = {
  mode: "hold",
  recipients: [],
  selectedGroups: [],
  returnStyle: null,
  audienceCircles: [],
  audienceUngrouped: [],
  reconnectPeriodId: null,
  goingQuietRecipients: [],
  recipientCircleOverrides: {}
};

/**
 * Rebuilds the per-person Going Quiet list from the currently selected Circles,
 * preserving any include/personalise choice already made for someone who's still
 * in scope, dropping anyone no longer in any selected Circle, and defaulting
 * anyone newly in scope to included with no personalised message.
 *
 * `overrides` (contactId -> target circleId) are applied FIRST, ahead of the
 * normal per-Circle pass below — a contact split into a new provisional
 * Circle is still a real member of their original Circle's contact list
 * (that's never mutated), so without this, the normal pass would silently
 * reattach them to their original Circle every time this recomputes. See
 * docs/09-decision-log.md, 2026-08-11.
 */
function mergeGoingQuietRecipients(
  existing: GoingQuietRecipient[],
  selectedGroups: CircleGroup[],
  overrides: Record<string, string> = {}
): GoingQuietRecipient[] {
  const existingByContactId = new Map(existing.map((recipient) => [recipient.contactId, recipient]));
  const groupsById = new Map(selectedGroups.map((group) => [group.id, group]));
  const seen = new Set<string>();
  const merged: GoingQuietRecipient[] = [];

  for (const [contactId, targetCircleId] of Object.entries(overrides)) {
    const targetGroup = groupsById.get(targetCircleId);
    const contact = targetGroup?.contacts.find((existingContact) => existingContact.id === contactId);
    if (!targetGroup || !contact || seen.has(contact.phoneNumber)) continue;

    seen.add(contact.phoneNumber);
    merged.push({
      contactId: contact.id,
      name: contact.name,
      phoneNumber: contact.phoneNumber,
      circleId: targetGroup.id,
      circleName: targetGroup.name,
      included: true,
      individuallyRemoved: false,
      instantMessage: "",
      routeToPersonalise: false
    });
  }

  for (const group of selectedGroups) {
    for (const contact of group.contacts) {
      if (seen.has(contact.phoneNumber)) continue;
      seen.add(contact.phoneNumber);

      const previous = existingByContactId.get(contact.id);
      merged.push(
        previous ?? {
          contactId: contact.id,
          name: contact.name,
          phoneNumber: contact.phoneNumber,
          circleId: group.id,
          circleName: group.name,
          included: true,
          individuallyRemoved: false,
          instantMessage: "",
          routeToPersonalise: false
        }
      );
    }
  }

  return merged;
}

/**
 * Real bug found and fixed (2026-08-13): a contact split into a new
 * provisional Circle mid-Going-Quiet (splitRecipientsIntoNewCircle) was
 * never actually removed from their ORIGINAL Circle's own `contacts` array
 * — that array is deliberately never mutated, since `overrides` was always
 * meant to be the source of truth for who's reassigned where. Going
 * Quiet's own session-send already respected that correctly (via
 * mergeGoingQuietRecipients' dedupe), but this function — which builds the
 * PERSISTED audience Reconnect reads from — didn't apply the same
 * exclusion, so the persisted record ended up with the same person listed
 * under both Circles at once. Confirmed on-device: this produced a
 * duplicate person id across two AudienceCircles in Reconnect's own pill
 * row (a React "duplicate key" warning), and — since Reconnect's
 * includedPersonIds is a single flat set keyed by phone number, not scoped
 * per Circle — toggling the shared person via their ORIGINAL Circle's chip
 * also flipped the NEW Circle's own "everyone included" read, which is
 * what actually produced "selecting Amin also selects New Circle". `overrides`
 * (contactId -> the Circle they were reassigned to) now excludes a contact
 * from any Circle that isn't their assigned one, mirroring
 * mergeGoingQuietRecipients' own precedence exactly. See
 * docs/09-decision-log.md, 2026-08-13.
 */
export function buildAudienceCircles(
  groups: CircleGroup[],
  overrides: Record<string, string> = {},
  excludedContactIds: ReadonlySet<string> = new Set()
): AudienceCircle[] {
  return groups.map((group) => ({
    circleId: group.id,
    circleName: group.name,
    contacts: group.contacts
      .filter((contact) => {
        const targetCircleId = overrides[contact.id];
        if (targetCircleId && targetCircleId !== group.id) return false;
        // Real bug found and fixed (2026-08-13): this only ever checked
        // `overrides` (reassignment to a different Circle) — a contact
        // excluded via toggleRecipientIncluded (included: false) but
        // never reassigned anywhere stayed fully present in the
        // PERSISTED audience regardless, contradicting the documented
        // "frozen onto the HoldPeriod record at send time" intent
        // (docs/09-decision-log.md, the original "Persisted audience,
        // not re-picked" entry). Excluded-and-not-reassigned now drops
        // them from this Circle's persisted contacts entirely — they
        // were only ever excluded for this one session/period, not
        // removed from the real Circle itself, so they're included
        // again by default next time. See docs/09-decision-log.md.
        return !excludedContactIds.has(contact.id);
      })
      .map((contact) => ({ name: contact.name, phoneNumber: contact.phoneNumber })),
    sendAsGroup: group.sendAsGroup ?? false
  }));
}

export function dedupeContactsByPhoneNumber(groups: CircleGroup[]): AudienceContact[] {
  const seen = new Map<string, AudienceContact>();

  for (const group of groups) {
    for (const contact of group.contacts) {
      if (!seen.has(contact.phoneNumber)) {
        seen.set(contact.phoneNumber, { name: contact.name, phoneNumber: contact.phoneNumber });
      }
    }
  }

  return Array.from(seen.values());
}

const HoldFlowContext = createContext<HoldFlowContextValue | null>(null);

export function HoldFlowProvider({ children }: PropsWithChildren) {
  const [state, setState] = useState<HoldFlowState>(initialState);

  const value = useMemo<HoldFlowContextValue>(
    () => ({
      ...state,
      setRecipients: (recipients) =>
        setState((current) => ({ ...current, recipients })),
      toggleGroup: async (group) => {
        const alreadySelected = state.selectedGroups.some((existing) => existing.id === group.id);

        if (alreadySelected) {
          setState((current) => {
            const selectedGroups = current.selectedGroups.filter((existing) => existing.id !== group.id);
            return {
              ...current,
              selectedGroups,
              recipients: dedupeContactsByPhoneNumber(selectedGroups).map((contact) => contact.name),
              goingQuietRecipients: mergeGoingQuietRecipients(
                current.goingQuietRecipients,
                selectedGroups,
                current.recipientCircleOverrides
              )
            };
          });
          return;
        }

        setState((current) => {
          const selectedGroups = [...current.selectedGroups, group];
          return {
            ...current,
            selectedGroups,
            recipients: dedupeContactsByPhoneNumber(selectedGroups).map((contact) => contact.name),
            goingQuietRecipients: mergeGoingQuietRecipients(
              current.goingQuietRecipients,
              selectedGroups,
              current.recipientCircleOverrides
            )
          };
        });
      },
      setSelectedGroups: (selectedGroups) =>
        setState((current) => ({
          ...current,
          selectedGroups,
          recipients: dedupeContactsByPhoneNumber(selectedGroups).map((contact) => contact.name),
          goingQuietRecipients: mergeGoingQuietRecipients(
            current.goingQuietRecipients,
            selectedGroups,
            current.recipientCircleOverrides
          )
        })),
      updateSelectedGroup: (updatedGroup) =>
        setState((current) => {
          const selectedGroups = current.selectedGroups.map((existing) =>
            existing.id === updatedGroup.id ? updatedGroup : existing
          );
          return {
            ...current,
            selectedGroups,
            recipients: dedupeContactsByPhoneNumber(selectedGroups).map((contact) => contact.name),
            goingQuietRecipients: mergeGoingQuietRecipients(
              current.goingQuietRecipients,
              selectedGroups,
              current.recipientCircleOverrides
            )
          };
        }),
      toggleRecipientIncluded: (contactId, fallbackMessage) =>
        setState((current) => ({
          ...current,
          goingQuietRecipients: current.goingQuietRecipients.map((recipient) => {
            if (recipient.contactId !== contactId) return recipient;

            const nowIncluded = !recipient.included;
            if (nowIncluded) {
              // Rejoining the group message — the individual state underneath is moot.
              return {
                ...recipient,
                included: true,
                individuallyRemoved: false,
                routeToPersonalise: false
              };
            }

            return {
              ...recipient,
              included: false,
              instantMessage: recipient.instantMessage || fallbackMessage || ""
            };
          })
        })),
      setRecipientIndividuallyRemoved: (contactId, removed) =>
        setState((current) => ({
          ...current,
          goingQuietRecipients: current.goingQuietRecipients.map((recipient) =>
            recipient.contactId === contactId ? { ...recipient, individuallyRemoved: removed } : recipient
          )
        })),
      setRecipientInstantMessage: (contactId, message) =>
        setState((current) => ({
          ...current,
          goingQuietRecipients: current.goingQuietRecipients.map((recipient) =>
            recipient.contactId === contactId ? { ...recipient, instantMessage: message } : recipient
          )
        })),
      setRecipientRouteToPersonalise: (contactId, route) =>
        setState((current) => ({
          ...current,
          goingQuietRecipients: current.goingQuietRecipients.map((recipient) =>
            recipient.contactId === contactId ? { ...recipient, routeToPersonalise: route } : recipient
          )
        })),
      splitRecipientsIntoNewCircle: (contactIds, group) =>
        setState((current) => {
          const recipientCircleOverrides = { ...current.recipientCircleOverrides };
          for (const contactId of contactIds) {
            recipientCircleOverrides[contactId] = group.id;
          }

          const selectedGroups = [...current.selectedGroups, group];
          return {
            ...current,
            selectedGroups,
            recipientCircleOverrides,
            recipients: dedupeContactsByPhoneNumber(selectedGroups).map((contact) => contact.name),
            goingQuietRecipients: mergeGoingQuietRecipients(
              current.goingQuietRecipients,
              selectedGroups,
              recipientCircleOverrides
            )
          };
        }),
      setReturnStyle: (returnStyle) =>
        setState((current) => ({ ...current, returnStyle })),
      setAudience: (audienceCircles, audienceUngrouped, reconnectPeriodId) =>
        setState((current) => ({ ...current, audienceCircles, audienceUngrouped, reconnectPeriodId })),
      resetFlow: (mode) =>
        setState({
          ...initialState,
          mode
        })
    }),
    [state]
  );

  return (
    <HoldFlowContext.Provider value={value}>
      {children}
    </HoldFlowContext.Provider>
  );
}

export function useHoldFlow(): HoldFlowContextValue {
  const value = useContext(HoldFlowContext);

  if (!value) {
    throw new Error("useHoldFlow must be used inside HoldFlowProvider");
  }

  return value;
}
