/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/create/done`; params?: Router.UnknownInputParams; } | { pathname: `/create/people`; params?: Router.UnknownInputParams; } | { pathname: `/create/review`; params?: Router.UnknownInputParams; } | { pathname: `/return/done`; params?: Router.UnknownInputParams; } | { pathname: `/return/update`; params?: Router.UnknownInputParams; } | { pathname: `/return/transition`; params?: Router.UnknownInputParams; } | { pathname: `/return/conversations`; params?: Router.UnknownInputParams; } | { pathname: `/return/reply/edit`; params?: Router.UnknownInputParams; } | { pathname: `/return/reply`; params?: Router.UnknownInputParams; } | { pathname: `/settings/circle/detail`; params?: Router.UnknownInputParams; } | { pathname: `/settings/circle`; params?: Router.UnknownInputParams; } | { pathname: `/settings/history`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/about`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/create/done`; params?: Router.UnknownOutputParams; } | { pathname: `/create/people`; params?: Router.UnknownOutputParams; } | { pathname: `/create/review`; params?: Router.UnknownOutputParams; } | { pathname: `/return/done`; params?: Router.UnknownOutputParams; } | { pathname: `/return/update`; params?: Router.UnknownOutputParams; } | { pathname: `/return/transition`; params?: Router.UnknownOutputParams; } | { pathname: `/return/conversations`; params?: Router.UnknownOutputParams; } | { pathname: `/return/reply/edit`; params?: Router.UnknownOutputParams; } | { pathname: `/return/reply`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/circle/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/circle`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/history`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/about${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/create/done${`?${string}` | `#${string}` | ''}` | `/create/people${`?${string}` | `#${string}` | ''}` | `/create/review${`?${string}` | `#${string}` | ''}` | `/return/done${`?${string}` | `#${string}` | ''}` | `/return/update${`?${string}` | `#${string}` | ''}` | `/return/transition${`?${string}` | `#${string}` | ''}` | `/return/conversations${`?${string}` | `#${string}` | ''}` | `/return/reply/edit${`?${string}` | `#${string}` | ''}` | `/return/reply${`?${string}` | `#${string}` | ''}` | `/settings/circle/detail${`?${string}` | `#${string}` | ''}` | `/settings/circle${`?${string}` | `#${string}` | ''}` | `/settings/history${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/about`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/create/done`; params?: Router.UnknownInputParams; } | { pathname: `/create/people`; params?: Router.UnknownInputParams; } | { pathname: `/create/review`; params?: Router.UnknownInputParams; } | { pathname: `/return/done`; params?: Router.UnknownInputParams; } | { pathname: `/return/update`; params?: Router.UnknownInputParams; } | { pathname: `/return/transition`; params?: Router.UnknownInputParams; } | { pathname: `/return/conversations`; params?: Router.UnknownInputParams; } | { pathname: `/return/reply/edit`; params?: Router.UnknownInputParams; } | { pathname: `/return/reply`; params?: Router.UnknownInputParams; } | { pathname: `/settings/circle/detail`; params?: Router.UnknownInputParams; } | { pathname: `/settings/circle`; params?: Router.UnknownInputParams; } | { pathname: `/settings/history`; params?: Router.UnknownInputParams; };
    }
  }
}
