/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `/create/done`; params?: Router.UnknownInputParams; } | { pathname: `/create/people`; params?: Router.UnknownInputParams; } | { pathname: `/return/done`; params?: Router.UnknownInputParams; } | { pathname: `/return/reconnect`; params?: Router.UnknownInputParams; } | { pathname: `/return/transition`; params?: Router.UnknownInputParams; } | { pathname: `/return/update`; params?: Router.UnknownInputParams; } | { pathname: `/settings/hold-plus`; params?: Router.UnknownInputParams; } | { pathname: `/settings/mission`; params?: Router.UnknownInputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/settings/research`; params?: Router.UnknownInputParams; } | { pathname: `/settings/circle/detail`; params?: Router.UnknownInputParams; } | { pathname: `/settings/circle`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownOutputParams; } | { pathname: `/create/done`; params?: Router.UnknownOutputParams; } | { pathname: `/create/people`; params?: Router.UnknownOutputParams; } | { pathname: `/return/done`; params?: Router.UnknownOutputParams; } | { pathname: `/return/reconnect`; params?: Router.UnknownOutputParams; } | { pathname: `/return/transition`; params?: Router.UnknownOutputParams; } | { pathname: `/return/update`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/hold-plus`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/mission`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/research`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/circle/detail`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/circle`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/history${`?${string}` | `#${string}` | ''}` | `/history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/library${`?${string}` | `#${string}` | ''}` | `/library${`?${string}` | `#${string}` | ''}` | `/create/done${`?${string}` | `#${string}` | ''}` | `/create/people${`?${string}` | `#${string}` | ''}` | `/return/done${`?${string}` | `#${string}` | ''}` | `/return/reconnect${`?${string}` | `#${string}` | ''}` | `/return/transition${`?${string}` | `#${string}` | ''}` | `/return/update${`?${string}` | `#${string}` | ''}` | `/settings/hold-plus${`?${string}` | `#${string}` | ''}` | `/settings/mission${`?${string}` | `#${string}` | ''}` | `/settings/privacy${`?${string}` | `#${string}` | ''}` | `/settings/research${`?${string}` | `#${string}` | ''}` | `/settings/circle/detail${`?${string}` | `#${string}` | ''}` | `/settings/circle${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/history` | `/history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/library` | `/library`; params?: Router.UnknownInputParams; } | { pathname: `/create/done`; params?: Router.UnknownInputParams; } | { pathname: `/create/people`; params?: Router.UnknownInputParams; } | { pathname: `/return/done`; params?: Router.UnknownInputParams; } | { pathname: `/return/reconnect`; params?: Router.UnknownInputParams; } | { pathname: `/return/transition`; params?: Router.UnknownInputParams; } | { pathname: `/return/update`; params?: Router.UnknownInputParams; } | { pathname: `/settings/hold-plus`; params?: Router.UnknownInputParams; } | { pathname: `/settings/mission`; params?: Router.UnknownInputParams; } | { pathname: `/settings/privacy`; params?: Router.UnknownInputParams; } | { pathname: `/settings/research`; params?: Router.UnknownInputParams; } | { pathname: `/settings/circle/detail`; params?: Router.UnknownInputParams; } | { pathname: `/settings/circle`; params?: Router.UnknownInputParams; };
    }
  }
}
